image: ubuntu:16.04

before_script:
- apt-get update -yqq
- apt-get install sudo git subversion build-essential libncurses5-dev zlib1g-dev gawk unzip libxml-perl flex wget gawk libncurses5-dev gettext quilt python libssl-dev rsync -yqq

build:
    stage: build
    script:
     - chown -R nobody .
     - sudo -u nobody make -j$(grep ^processor /proc/cpuinfo | wc -l)
     - cd lede; sudo -u nobody make clean
    artifacts:
     paths:
      - firmwares
#    cache:
#      paths:
#      - lede
#      key: "$CI_BUILD_REF_NAME"

deploy:
    stage: deploy
    script:
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s) 
     - ssh-add <(echo "${SSH_PRIVATE_KEY}") 
     - echo "${SSH_HOST_KEY}" > hostkey 
     - rsync -hrvz -e 'ssh -o "UserKnownHostsFile hostkey"' firmwares firmware@weimarnetz.segfault.gq:/home/firmware/public_html/

