image: ubuntu:16.04

before_script:
- apt-get update -yqq
- apt-get install git subversion build-essential libncurses5-dev zlib1g-dev gawk unzip libxml-perl flex wget gawk libncurses5-dev gettext quilt python libssl-dev -yqq

build:
    stage: build
    script: 
     - make -j $(nproc) V=s 
    artifacts:
     paths:
      - lede/firmware

