image: ubuntu:16.04

before_script:
- apt-get update -yqq
- apt-get install sudo git subversion build-essential libncurses5-dev zlib1g-dev gawk unzip libxml-perl flex wget gawk libncurses5-dev gettext quilt python libssl-dev rsync -yqq

stages:
  - build
  - deploy

build:
    stage: build
    script:
     - chown -R nobody .
     - sudo -u nobody make TARGET=ar71xx -j$(nproc) 
#     - sudo -u nobody make TARGET=ramips_mt7260 -j$(nproc)
#     - sudo -u nobody make TARGET=ramips_mt7628 -j$(nproc)
#     - sudo -u nobody make TARGET=x86 -j$(nproc)
#     - sudo -u nobody make TARGET=uml -j$(nproc)

    artifacts:
     paths:
      - firmwares
     expire_in: 1 day

deploy:
    stage: deploy
    script:
     - eval $(ssh-agent -s) 
     - ssh-add <(echo "${SSH_PRIVATE_KEY}") 
     - echo "${SSH_HOST_KEY}" > hostkey 
     - rsync -hrvz -e 'ssh -o "UserKnownHostsFile hostkey"' firmwares firmware@weimarnetz.segfault.gq:/
