image: ubuntu:16.04

before_script:
- apt-get update -yqq
- apt-get install sudo git subversion build-essential libncurses5-dev zlib1g-dev gawk unzip libxml-perl flex wget gawk libncurses5-dev gettext quilt python libssl-dev -yqq

build:
    stage: build
    script:
     - chown -R nobody .
     - sudo -u nobody make -j$(grep ^processor /proc/cpuinfo | wc -l)
     - sudo -u nobody lede/make clean
    artifacts:
     paths:
      - firmwares
    cache:
      paths:
      - lede
      key: "$CI_BUILD_REF_NAME"

